[package]
name = "stormrfb-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
[package.metadata]
cargo-fuzz = true
[dependencies]
libfuzzer-sys = "0.4"
stormrfb = { path = "../crates/stormrfb" }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
[workspace]
[[bin]]
name = "decoder"
path = "fuzz_targets/decoder.rs"
test = false
doc = false
bench = false
